// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdooWorkerService.DataAccess;

#nullable disable

namespace OdooWorkerService.Migrations
{
    [DbContext(typeof(LeociaEmployeesContext))]
    [Migration("20240718100551_addColumnOdooId")]
    partial class addColumnOdooId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OdooWorkerService.Entities.HrEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AdditionalNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AddressHomeId")
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int?>("BankAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Certificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Children")
                        .HasColumnType("int");

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<int?>("Color")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<bool?>("ContractWarning")
                        .HasColumnType("bit");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryOfBirth")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUid")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartureReasonId")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExpenseManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstContractDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdOdoo")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KmHomeWork")
                        .HasColumnType("int");

                    b.Property<int?>("LastAttendanceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LeaveManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Marital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MessageMainAttachmentId")
                        .HasColumnType("int");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilityCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PassportId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermitNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResourceCalendarId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<string>("Sinid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SpouseBirthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpouseCompleteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ssnid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudySchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Vehicle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VisaExpire")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkContactId")
                        .HasColumnType("int");

                    b.Property<string>("WorkEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WorkPermitExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("WorkPermitScheduledActivity")
                        .HasColumnType("bit");

                    b.Property<string>("WorkPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("WriteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WriteUid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("hrEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
